#!/usr/bin/env bash
# Configures domain zone so that the subdomain www points to load-balancer IP (lb-01)

command -v dig >/dev/null 2>&1 || { echo >&2 "dig is required but it's not installed. Aborting."; exit 1; }

print_info () {
    local subdomain="$1"
    local domain="$2"
    local result
    result=$(dig "$subdomain" | grep -A1 'ANSWER SECTION:' | sed -r "s/$subdomain\./$domain/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }')
    if [ -n "$result" ]; then
        echo "$result"
    else
        echo "Failed to retrieve information for $subdomain.$domain"
    fi
}

if [ "$#" -eq 2 ]
then
    print_info "$2.$1" "$2"
else
    print_info "www.$1" "www"
    print_info "lb-01.$1" "lb-01"
    print_info "web-01.$1" "web-01"
    print_info "web-02.$1" "web-02"
fi
