#!/usr/bin/env bash                                                                                                                                       
# Fix Ubuntu container’s Nginx installation port 80                                                                                                             
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                            
rm default;                                                                                                                                                                           
ln -s /etc/nginx/sites-available/default default;                                                                                       
service nginx restart 
