#!/usr/bin/env bash
# Displays a list of currently running processes.
#   Shows all processes, for all users, including those with no TTY.

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

ps aux | head -50
