#!/usr/bin/env bash
# Displays the PID along with the process name, of 
#+ processes whose name contains the word "bash".

pids=$(pgrep -f bash)

echo "PID   Process Name"
for pid in $pids; do
    process_name=$(ps -o comm= -p $pid)
    echo "$pid    $process_name"
done
