#!/usr/bin/env bash
# Script that configures the container
pkill apache2 >/dev/null 2>&1
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf 
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo service nginx restart